package com.leoyas.geolocatorservice;

import com.leoyas.geolocatorservice.dao.UserRepository;
import com.leoyas.geolocatorservice.model.User;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.annotation.DirtiesContext;

import static org.junit.jupiter.api.Assertions.assertTrue;

@SpringBootTest
@DirtiesContext
public class MongoDbAutoGeneratedFieldIntegrationTest {

    @Autowired
    UserRepository userRepository;

    @Test
    public void contextLoads() {
    }

    @Test
    public void givenUserObject_whenSave_thenCreateNewUser() {

        User user = new User();
        user.setFirstName("Leo");
        user.setLastName("Yassuda");
        user.setEmail("leo.yassuda@example.com");
        userRepository.save(user);
        userRepository.findAll().count().subscribe(allUsers -> {
          assertTrue(allUsers > 0);
        });

    }

}
